### ISSUE TITLE
Missing Mobile Super X2 pickup

### ISSUE THREAD

**Issue by TrueHitoare** [thezerothcat/LaMulanaRandomizer#29]
In a seed where the Mobile Super X2 was an item to be picked up rather than bought, there was no item present, and the upgrade couldn't be collected.

**Comment by TrueHitoare** [comment]
For this specific instance, the Bomb was replaced by the Mobile Super X2. After defeating Kamaitachi, the weapon block disappeared, but no item was present.

Possibly related to the fact that the Mobile Super X2 doesn't show up in your inventory. May be something that means it only works properly in shops. Uncertain if there's any difference between having it show up in a weapon block vs. in a chest vs. as an Ancient Software download.

Version: 1.8.2
Seed: 1549014844
Item Settings: Holy Grail, Hand Scanner, reader.exe in Original Positions, other items Random
Advanced Settings: Allow damage-boosting requirements off, others on
Shop Randomization: Unique items only
Glitch settings: All off
Boss Difficulty: Lower

**Comment by thezerothcat** [comment]
I'm pretty sure I've seen it picked up successfully, at least from a chest. I'm also pretty sure you'd already purchased the item in the MSX2 shop slot (I went back and watched some of the earlier parts of the stream, although I'm not at the end yet), so my still-untested theory is that the item disappears if you've purchased the thing from the shop.

It's going to be a pain to test since I need to defeat 4 bosses first, but I'll definitely look into it.

**Comment by TrueHitoare** [comment]
Can confirm that we bought the computer shop item first, as it was the Plane Model, which we needed to reach the Bomb location in the first place. That seems like a strong possibility.

**Comment by thezerothcat** [comment]
Oh right, this is *that* shop. The post-purchase dialog for the item actually sets a flag to indicate that you've purchased the item (it's the only instance of that happening in the entire game, I believe). I thought I'd fixed it, but apparently I was wrong. It should be fixed in 1.9.3+
