### ISSUE TITLE
Potential softlock from Temple of the Sun map chest

### ISSUE THREAD

**Issue by TrueHitoare** [thezerothcat/LaMulanaRandomizer#32]
Climbed down into the area where the Temple of the Sun map normally is, but then realized I forgot to unlock the chest first, and warped out and saved without thinking. Now the ladder is permanently gone and I can no longer access the (normally optional) item there (which is the Life Seal in this seed). Neither leaving the area nor restarting the program brought back the ladder.

[randomizer-config.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/1297300/randomizer-config.txt)

**Comment by thezerothcat** [comment]
Yes, this has always been a thing, even in the original game. I'm aware of it, but not going out of my way to prevent a softlock that has nothing to do with randomizer changes...at least not right now. Maybe eventually I can try to prevent the ladder from de-spawning or something.

**Comment by TrueHitoare** [comment]
In the original game, the chest contained the Map for Temple of the Sun, which was a fully optional item, so it didn't matter if you lost access to it. Randomizer making it potentially be a required item introduces a potential softlock where one didn't exist before.

Easiest solution is just to make it so required items can't be in that chest.

**Comment by thezerothcat** [comment]
You do have a point, but it's actually a bit more complicated than you might think. That's not the only permanently missable chest in the game - you also have Chain Whip, Flail Whip, and Angel Shield (there's no guarantee that the player has access to the far part of Gate of Time when they fail the puzzle), the untransformed Spring in the Sky shop (I've had requests to limit that as well, but I've also had requests to not limit it), and potentially any chest in Shrine of the Mother. If I restrict the map chest, then I should probably restrict those other locations for the sake of consistency.

Additionally, there is the question of what's actually required. In the original game, Chain Whip and Flail Whip were considered optional, but in randomizer, I don't expect many people would be pleased if their Flail Whip was in the map chest and they broke it.  There are also some seemingly-unnecessary items which can conditionally be required, such as randc if the revive combo is used in place of a sacred orb.

The safest thing to do would be to make the chest not be randomized or have it contain strictly useless things like maps, maybe xmailer or guild software (even bounce can be useful if you're out of bombs and want to grab an attack fairy to blow up a wall for you), but that doesn't make for very interesting randomization - a lot of people would probably not even bother getting it at that point (to an even greater degree with Chain Whip if I gave it the same treatment).

Rather than try to work through all of that, I'd rather leave this one alone for now, and maybe eventually fix the ladder. (I'd also like to eventually make the old Spring shop accessible after you use the Key Fairy on it, so maybe I'll revisit this then?)

**Comment by smurfton** [comment]
The safest thing to do would be to replace the ladder's disappearance with a screen flag. That way it resets.

**Comment by thezerothcat** [comment]
That's a very good point. I'll look into it. Thanks!
