### ISSUE TITLE
Unwinnable seed on 1.18.2

### ISSUE THREAD

**Issue by spinachislove** [thezerothcat/LaMulanaRandomizer#49]
[103802299.zip](https://github.com/thezerothcat/LaMulanaRandomizer/files/1503218/103802299.zip) (includes save)
It looks like some requirements still need to be adjusted. I checked the spoiler because I couldn't get any further, and I found the following chain:
Fruit of Eden (Treasure location) requires Pepper (Ankh (D Corr.) loc.) requires Helmet (to defeat all minibosses; Dim. Key location) requires Mulana Talisman (Discount shop in Sun's) requires Death Seal (Birth Shop) requires Fruit of Eden to animate the mudmen.
Note that I'm allowing Cat pause and lamp glitch, but I haven't been able to use them to get into Confusion gate from Tower of the Goddess, and glitching into Death Shop and Musshussu (sp?) didn't work either.

**Comment by dansidney** [comment]
Are you enabling Raindrop glitch? You otherwise can escape in the mermaid miniboss room from underwater, you don't strictly need the helmet. It's hard but feasible.

**Comment by spinachislove** [comment]
The only enabled glitches are Lamp glitch and Cat pause.
And how would you actually kill the miniboss? I think you have to go into the water to trigger his appearance, so it would be very luck-dependent (no scale sphere makes it even worse).

**Comment by dansidney** [comment]
You need to fall to the side of the room and yes, in short you need to get lucky. Still if you didn't enable RainDropping, then it is a deadlock condition.

**Comment by dansidney** [comment]
You need to fall to the side of the room in a precise manner.

https://clips.twitch.tv/SwissPerfectGarbageBabyRage

Still if you didn't enable RainDropping, then it is a deadlock condition.

**Comment by spinachislove** [comment]
Huh. I would never have thought of that. Thanks for the tips, even if the seed is likely screwed.

**Comment by thezerothcat** [comment]
Sorry for the late response.

From the sound of things, you still have options. The miniboss can definitely be fought without Helmet if you have ranged weapons; you have to go down the ladder instead of falling into the room. Here's a clip of naruminhai triggering the fight: https://clips.twitch.tv/FancyTrustworthyOrcaPrimeMe

I think that will get you unstuck for this seed, but just in case you're not aware, if you can use Lamp glitch and have Feather, it's possible to get into the lower part of Confusion Gate/Gate of Illusion without Fruit of Eden. You can't unlock the upper area until you get Fruit of Eden (aside from some difficult tricks the randomizer doesn't support yet), but there are a couple of things you can get in the lower area.

For the Lamp glitch setup above, I do realize now that I failed to include damage boosting (off the divine retribution block) as a requirement. I should probably also include Grapple Claw so people won't be required to time the double jump/damage boost, so I'll do that for the next build.

Thanks!

**Comment by spinachislove** [comment]
Defeating the miniboss (and leaving after) did indeed work with the ladder entrance. Thanks!
I have to ask though, how would you get into lower Confusion gate without fruit? My google-fu is weak. From what you say I suspect via Graveyard of the Giants, damage-boosting into the block somehow?

And it really has nothing to do with this, but do you think it would be possible/practically feasible to allow the player to "turn off" certain treasures after you get them (Spaulder in particular)? Or maybe even adding an option that makes the Spaulder not do anything. Usually avoiding picking stuff up isn't an issue, but it really sucks when you get it from the hidden chest in Tower. Just a minor thing, but not worrying about picking up bad things would be a nice QoL improvement.

**Comment by dansidney** [comment]
Another vote to rename the randomizer to "Where is the Spaulder?" .

**Comment by thezerothcat** [comment]
Yeah, getting rid of Spaulder is probably my most common feature request.

I have plans to make it possible to remove some (configurable) items from the pool including Spaulder, but I haven't coded it yet. Excluded items would be replaced with weight chests (similar to maps), and in the case of non-chest items, I'll need to a way to notify the player that they won't be getting an item (for non-buggy reasons).

As for Graveyard of the Giants, you use lamp glitch to disable collision on the illusion fruit block, double jump into the block, grapple the wall until lamp expires (or time your jump), and then hit the block with your weapon to get transitioned up by divine retribution.
