### ISSUE TITLE
Graphical errors on backside gates.

### ISSUE THREAD

**Issue by goldencow2** [thezerothcat/LaMulanaRandomizer#85]
This is a Viy-locked gate to Endless Corridor. 
[randomizer-config.txt](https://github.com/thezerothcat/LaMulanaRandomizer/files/2959974/randomizer-config.txt)

![Untitled](https://user-images.githubusercontent.com/43799724/54257292-db33e680-452c-11e9-93c6-bb4fe745b99a.png)

**Comment by thezerothcat** [comment]
I've been getting some occasional reports of this, and as far as I can tell, one of the previous versions of the randomizer had a bug that caused it to modify the backup instead of only the graphics file that was actually in use.

It's messed up the file size in a way I can't restore from the randomizer itself, so your options for restoring the graphics file in question are to reinstall, or to go to your Install Directory and then navigate to data/graphics/00 (or a different number if you're using graphics mods) and replace 01effect.png.

The bug with modifying the backup is fixed now, at least as far as I've seen, so you shouldn't have to do this again in the future. Sorry for the inconvenience!

![01effect](https://user-images.githubusercontent.com/29313340/54316685-fd6a4a80-45a6-11e9-9cf3-40c28cb484cb.png)
